<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Common objects for web framework</Description>

        <VersionPrefix>1.2.8</VersionPrefix>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
