name: "Build + Publish NuGet Package"
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "*.sln"
      - "*.slnx"
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "*.sln"
      - "*.slnx"

env:
  DOTNET_NOLOGO: true

jobs:
  get-head-commit-message:
    runs-on: "ubuntu-latest"
    outputs:
      head-commit-message: ${{ steps.get-head-commit-details.outputs.head-commit }}
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get Head Commit message
        id: get-head-commit-details
        run: >
          {
            echo 'head-commit<<EOF'
            git log -1 --pretty=%B
            echo EOF
          } >> "$GITHUB_OUTPUT"

  build:
    runs-on: "rbx-local" # Due to local NuGet
    if: ${{ !contains(needs.get-head-commit-message.outputs.head-commit-message, '#!skip-build!#') }}
    needs: get-head-commit-message
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # Build
      - name: Restore NuGet Packages
        run: >-
          dotnet restore

      - name: Build Solution (Release)
        run: >-
          dotnet build
          --no-restore
          -c Release

      - name: Run Tests
        run: >-
          dotnet test
          --no-build
          --no-restore
          -c Release

      - name: Pack NuGet Packages
        run: >-
          dotnet pack
          --no-build
          --no-restore
          --output ./dist
          -c Release
          -p:IncludeSymbols=true
          -p:SymbolPackageFormat=snupkg

      - name: Build Solution (Debug)
        run: >-
          dotnet build
          --no-restore
          -c Debug
          -p:VersionSuffix=dev

      - name: Pack Debug NuGet Packages
        run: >-
          dotnet pack
          --no-build
          --no-restore
          --output ./dist
          -c Debug
          -p:IncludeSymbols=true
          -p:SymbolPackageFormat=snupkg
          -p:VersionSuffix=dev

      # Finish
      - name: Upload release build artifacts
        continue-on-error: true
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: release-nuget-packages
          path: |
            ./dist/*.nupkg
            ./dist/*.snupkg

  # Upload to NuGet (production feed)
  upload:
    runs-on: "rbx-local"
    needs: "build"
    if: ${{ github.event_name == 'push' }}
    steps:
      # Setup
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-nuget-packages
          path: dist

      - name: Publish NuGet Packages
        run: >-
          dotnet nuget push
          dist/*.nupkg
          --skip-duplicate
          --source ${{ vars.NUGET_SOURCE }}
          --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Clean up
        run: >-
          rm -rf dist
